### ISSUE TITLE
Page Suddenly Deleted When Using Excalidraw

### ISSUE THREAD

**Issue by espeletagm** [zsviczian/roam-excalidraw-issues#17] opened 2021-03-30 07:45 UTC
**Describe the bug**
When using Excalidraw, Roam will suddenly freeze, then it will delete all the content in the page where you use Excalidraw. In this case, it was daily notes

**To Reproduce**
1. Go to your daily notes
2. Add the Excalidraw block 
3. Use Excalidraw and add elements (9 text boxes, 6 arrows)
3.5 Duplicate elements and move across the board

4. Experience Roam freeze

**Expected behavior**

**Screenshots**
![Screen Shot 2021-03-30 at 3 48 58 PM](https://user-images.githubusercontent.com/81613817/112952776-724d5480-916f-11eb-97d4-d31126ba3d54.png)

**Desktop (please complete the following information):**
 - MacBook
 - Chrome
 - Latest version

**Additional context**
This happened twice within one hour. Roam was not updated to the latest.

**Comment by zsviczian** [comment] 2021-03-30 08:08
![image](https://user-images.githubusercontent.com/14358394/112954889-2387c680-913f-11eb-834c-ee0a6dceedbf.png)

The issue happens when you copy/paste large number of text blocks. There is a limit on the roamAPI as to the number of atomic changes within 60 seconds, and I do not handle this error

**Comment by espeletagm** [comment] 2021-03-30 08:09
[](url)

**Comment by espeletagm** [comment] 2021-03-30 08:10
@zsviczian thanks for letting me know. This makes sense to an extent. Thing was, I wasn't making a load of atomic changes, but still good to know thanks

P.S. This is my first time using github so sorry that I closed it earlier hah

**Comment by zsviczian** [comment] 2021-03-30 08:25
no worries. I will fix the issue regardless.
I think you can also continue to use Excalidraw in Roam, just until the fix is out... pause a bit if you are doing lots of changes.
Also if you want to add lots of text, a more efficient workflow is to close the drawing and add the nested text under the drawing in roam, then open the drawing to position the text. 

[see this animated gif as an example](https://roam-excalidraw.com/changelog/20210326/1.gif)

**Comment by zsviczian** [comment] 2021-03-31 16:56
text blocks were updated even if the text did not change. this resulted in an increasing number of changes as the amount of text on the drawing increased. The issue is now fixed in mvp.v04

**Closed as completed by zsviczian** 2021-03-31 16:56 UTC
Labels: bug
